### ISSUE TITLE
Accessibility of Chat Overlay

### ISSUE THREAD

**Issue by codebrainz** [CodingGarden/sproutkit#11]
There is code here to ensure correct contrast of messages, presumably for accessibility purposes:

https://github.com/CodingGarden/sproutkit/blob/master/src/lib/colors.ts

However when "focus mode" is activated, the chat overlay becomes virtually unreadable when watching the VODs, which is really frustrating to the viewers, especially those with poor eyesight. Also it seems it's still perfectly visible to @w3cj since he always just continues reading chat while in focus mode anyway :)

It would be great if the accessibility of the "focus mode" could be improved for people who can't catch the live streams and so have to rely on the chat overlay to read the chat.

**Comment by codebrainz** [comment]
@w3cj thanks for addressing this issue on stream. Dropping the blur and decreasing the opacity made it quite a bit more readable.

Do you want me to close this issue or should it wait until you commit/push the changes to do it?

Thanks!

**Comment by w3cj** [comment]
👍
