### ISSUE TITLE
Suggestion Clicking a message to open a modal

### ISSUE THREAD

**Issue by omar2205** [CodingGarden/sproutkit#14]
If someone asked a question this is a good way to highlight it

![image](https://user-images.githubusercontent.com/1373867/191388009-186c8232-04d4-4aa8-b549-16bda0f7cc1b.png)

**Comment by drillskibo** [comment]
This was already the case before and CJ decided to remove it.
I could link to older VODs with use cases.

**Comment by omar2205** [comment]
Closed as CJ showed it on stream
